<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNUsDdkB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNUsDdkB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNUsDdkB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNUsDdkB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNUsDdkB\App_KernelDevDebugContainer([
    'container.build_hash' => 'NUsDdkB',
    'container.build_id' => 'e0d6491e',
    'container.build_time' => 1696581633,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNUsDdkB');
