<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH8Xk8ho\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH8Xk8ho/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH8Xk8ho.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH8Xk8ho\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH8Xk8ho\App_KernelDevDebugContainer([
    'container.build_hash' => 'H8Xk8ho',
    'container.build_id' => '193a23ba',
    'container.build_time' => 1705598010,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH8Xk8ho');
